services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    container_name: jenkins
    build: 
      context: .
    user: root
    ports:
    - 8080:8080
    - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  web-app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/imo
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
      sh -c "python manage.py migrate"
      sh -c "python manage.py "

    depends_on:
      - database
  
  database:
    restart: unless-stopped
    image: postgres:15.1-alpine3.17
    environment:
      - POSTGRES_DB=imodb
      - POSTGRES_USER=imo
      - POSTGRES_PASSWORD=imoproject
  
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    restart: unless-stopped
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/imo
    links:
      - redis
    depends_on:
      - redis
    
  # flower:
  #   restart: unless-stopped
  #   build: 
  #     context: .
  #   hostname: flower
  #   entrypoint: celery
  #   command: -A celery_app.app flower
  #   volumes:
  #     - .:/imo
  #   links:
  #     - redis
  #   depends_on:
  #     - redis
  #   ports:
  #     - "5555:5555"