services:
  web-app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/imo
    
    environment:
      SECRET_KEY: "django-insecure-s^^#%xw(ui)n7lv9$$b67f7*h#y-jwe4$$c)foij$$-yg-etb#o3k"
      DB_HOST: "database"
      DB_NAME: "imo_db"
      DB_USER: "u_imo"
      DB_PASS: "test"
    
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 imo.wsgi"



  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    restart: unless-stopped
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/imo
      
    links:
      - redis
    depends_on:
      - redis
  
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - web-app
    ports:
      - "80:80"
    volumes:
      - ./mainsite/static:/var/u_imokai/html/static
      - ./configs/nginx.d:/etc/nginx/conf.d



  # flower:
  #   restart: unless-stopped
  #   build: 
  #     context: .
  #   hostname: flower
  #   entrypoint: celery
  #   command: -A celery_app.app flower
  #   volumes:
  #     - .:/imo
  #   links:
  #     - redis
  #   depends_on:
  #     - redis
  #   ports:
  #     - "5555:5555"