services:
  web-app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/imo
    
    environment:
      SECRET_KEY: "django-insecure-s^^#%xw(ui)n7lv9$$b67f7*h#y-jwe4$$c)foij$$-yg-etb#o3k"
      DB_HOST: "database"
      DB_NAME: "imo_db"
      DB_USER: "u_imo"
      DB_PASS: "test"
    
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 imo.wsgi"

    depends_on:
      - database


  database:
    restart: unless-stopped
    image: postgres:15.2
    environment:
      POSTGRES_DB: "imo_db"
      POSTGRES_USER: "u_imo"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U u_imo -d test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    restart: unless-stopped
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/imo
      
    links:
      - redis
    depends_on:
      - redis
  
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - web-app
    ports:
      - "80:80"
    volumes:
      - ./mainsite/static:/var/u_imokai/html/static
      - ./configs/nginx.d:/etc/nginx/conf.d


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "cooperative.entr@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - database

networks:
  database:
    driver: bridge


  # flower:
  #   restart: unless-stopped
  #   build: 
  #     context: .
  #   hostname: flower
  #   entrypoint: celery
  #   command: -A celery_app.app flower
  #   volumes:
  #     - .:/imo
  #   links:
  #     - redis
  #   depends_on:
  #     - redis
  #   ports:
  #     - "5555:5555"