services:
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   restart: unless-stopped
  #   privileged: true
  #   container_name: jenkins
  #   build: 
  #     context: .
  #   user: root
  #   volumes:
  #     - ./jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #   - 8080:8080
  #   - 50000:50000
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /home/u_imokai/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  web-app:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/imo
    
    environment:
      - SECRET_KEY=django-insecure-s^^#%xw(ui)n7lv9$$b67f7*h#y-jwe4$$c)foij$$-yg-etb#o3k
      - DB_HOST=database
      - DB_NAME=imo_db
      - DB_USER=u_imo
      - DB_PASS=test
    
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 imo.wsgi"

    depends_on:
      - database


  database:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_DB: "imo_db"
      POSTGRES_USER: "u_imo"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    restart: unless-stopped
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/imo
      
    links:
      - redis
    depends_on:
      - redis
  
  nginx:
    image: nginx:1.19.8-alpine
    depends_on:
      - web-app
    ports:
      - "80:80"
    volumes:
      - ./mainsite/static:/var/u_imokai/html/static
      - ./configs/ninx.d:/etc/nginx/conf.d
    
  # flower:
  #   restart: unless-stopped
  #   build: 
  #     context: .
  #   hostname: flower
  #   entrypoint: celery
  #   command: -A celery_app.app flower
  #   volumes:
  #     - .:/imo
  #   links:
  #     - redis
  #   depends_on:
  #     - redis
  #   ports:
  #     - "5555:5555"