# Generated by Django 4.0.3 on 2023-02-20 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fac_id', models.CharField(max_length=10)),
                ('docs', models.FileField(blank=True, null=True, upload_to='docs')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('question', models.TextField()),
                ('question_en', models.TextField(null=True)),
                ('question_ru', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gra_id', models.CharField(max_length=10)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Triadkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_edu', models.IntegerField(default='0')),
                ('type_edu', models.CharField(blank=True, choices=[('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура'), ('Асперантура', 'Асперантура')], max_length=12, null=True)),
                ('day_tipe', models.CharField(blank=True, choices=[('Очная', 'Очная'), ('Очно-вечерняя', 'Очно-вечерняя')], max_length=13, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('exam_one', models.CharField(blank=True, choices=[('MATH', 'Математика'), ('RUSS', 'Русский Язык'), ('CHEM', 'Химия'), ('PHYS', 'Физика'), ('SOCL', 'Обществознание'), ('INFO', 'Информатика'), ('FRLN', 'Иностранный язык')], max_length=14, null=True)),
                ('exam_two', models.CharField(blank=True, choices=[('MATH', 'Математика'), ('RUSS', 'Русский Язык'), ('CHEM', 'Химия'), ('PHYS', 'Физика'), ('SOCL', 'Обществознание'), ('INFO', 'Информатика'), ('FRLN', 'Иностранный язык')], max_length=14, null=True)),
                ('exam_three', models.CharField(blank=True, choices=[('MATH', 'Математика'), ('RUSS', 'Русский Язык'), ('CHEM', 'Химия'), ('PHYS', 'Физика'), ('SOCL', 'Обществознание'), ('INFO', 'Информатика'), ('FRLN', 'Иностранный язык')], max_length=14, null=True)),
                ('direction_choice', models.CharField(blank=True, choices=[('First-building', '1-е здание'), ('Second-building', '2-е здание'), ('Third-building', '3-е здание'), ('Fifth-building', '5-е здание'), ('Seveth-building', '7-е здание'), ('Eighth-building', '8-е здание')], max_length=16, null=True)),
                ('description', models.TextField()),
                ('key', models.CharField(max_length=10)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('faculty', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='mainsite.faculty')),
                ('graduate', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='graduate', to='mainsite.graduate')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Мужчина'), ('F', 'Женщина'), ('N', 'Не хочу говорить')], max_length=12, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('citizenship', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField()),
                ('text_en', models.TextField(null=True)),
                ('text_ru', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
