# Generated by Django 4.0.3 on 2022-11-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_post_text_en_post_text_ru_post_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
