# Generated by Django 4.0.3 on 2022-11-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_faq_question_en_faq_question_ru_faq_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_ru',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
