# Generated by Django 4.0.3 on 2022-06-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_rename_exam_speciality_exam_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='day_tipe',
            field=models.CharField(blank=True, choices=[('Очная', 'Очная'), ('Очно-вечерняя', 'Очно-вечерняя')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='exam_one',
            field=models.CharField(blank=True, choices=[('Математика', 'Математика'), ('Русский Язык', 'Русский Язык'), ('Химия', 'Химия'), ('Физика', 'Физика'), ('Обществознание', 'Обществознание'), ('Информатика', 'Информатика'), ('Иностранный язык', 'Иностранный язык')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='exam_three',
            field=models.CharField(blank=True, choices=[('Математика', 'Математика'), ('Русский Язык', 'Русский Язык'), ('Химия', 'Химия'), ('Физика', 'Физика'), ('Обществознание', 'Обществознание'), ('Информатика', 'Информатика'), ('Иностранный язык', 'Иностранный язык')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='exam_two',
            field=models.CharField(blank=True, choices=[('Математика', 'Математика'), ('Русский Язык', 'Русский Язык'), ('Химия', 'Химия'), ('Физика', 'Физика'), ('Обществознание', 'Обществознание'), ('Информатика', 'Информатика'), ('Иностранный язык', 'Иностранный язык')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='type_edu',
            field=models.CharField(blank=True, choices=[('Бакалавриат', 'Бакалавриат'), ('Магистратура', 'Магистратура'), ('Асперантура', 'Асперантура')], max_length=12, null=True),
        ),
    ]
